### ISSUE TITLE
Mouse clicks not recognized

### ISSUE THREAD

**Issue by TBruyn** [bluesabre/sgt-launcher#7]
I can open all the games of SGT puzzles, but once it is open there is no effect to my mouse clicks. There is no issue with opening any menu item, but neither left or right mouse clicks actually do anything.

I am running Pop!_OS, version 20.10.

**Comment by bluesabre** [comment]
Confirmed with Pop!_OS 21.04 and sgt-launcher 0.2.6. It seems like the embedded window never receives focus.

**Comment by bluesabre** [comment]
Same issue exists with Ubuntu 21.04 on Xorg. This seems like it could be a bug specific to GNOME.
