### ISSUE TITLE
Empty Launchers panel (Arch Linux)

### ISSUE THREAD

**Issue by wacker-muc** [bluesabre/sgt-launcher#9]
On Arch Linux (here I'm using Manjaro), the *.desktop" files are named "blackbox.desktop", "bridges.desktop", etc – without any prefix. Therefore, when get_launchers() searches for applications with a "sgt-" or "puzzle-" prefix, it will not find any.

Solution: Replace these three lines in SgtLauncher.py:

----
        for game in self.GAMES:
            for prefix in ["sgt", "puzzle"]:
                launcher = "applications/%s-%s.desktop" % (prefix, game)
----
        for game in self.GAMES:
            for prefix in ["sgt-", "puzzle-", ""]:
                launcher = "applications/%s%s.desktop" % (prefix, game)
----

**Comment by bluesabre** [comment]
Thanks for the bug report and suggestion. Tweaked a bit to ensure the launcher doesn't grab other desktop files (it's possible another package could provide any of these launchers). Tested on Xubuntu and Majaro.
